print("name")
name=input("add ur name:")
print("adres")
adres=input("add ur adres:")
print("postcode")
postcode=input("add ur postcode:")
print("woonplaats")
woonplaats=input("add ur woonplaats:")

print("_______________________________________________________________")
print("name :" +name)
print("adres:" +adres)
print("postcode:" +postcode)
print("woonplaats:" +woonplaats)
print("_______________________________________________________________")
